version: 1
accounts:
  - name: alice
    coins:
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000token
      - 100000000stake
  - name: miner
    coins:
      - 50000token
      - 500000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: alice
  coins:
    - 5token
    - 100000stake
genesis:
  chain_id: tokenchain-1
validators:
  - name: alice
    bonded: 100000000stake